version: "3"

services:
  backend:
    build:
      context: ./heavy-puzzle-backend
    ports:
      - "8000:8000"
    volumes:
      - "${STATIC_FILES_PATH}:/app/static"
  web:
    build:
      context: ./heavy-puzzle-web
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
